site_name: Phenox Library Documentation
theme: readthedocs
repo_url: https://github.com/phenoxlab/phenox/
site_description: Phenox Library Documentation
site_author: Ryo Konomura
site_favicon: 'favicon.ico'
pages:
- 'Home': 'index.md'
- Before You Start:
    - 'First': 'start/note.md'
    - 'Phenox Package Contents': 'start/package.md'
    - 'Hardware Overview': 'start/hardware.md'
#     - 'Circuit Overview': 'start/circuit.md'
#     - 'Principal Axes': 'start/directions.md'
#     - 'Power': 'start/power.md'
#     - 'Communication': 'start/com.md'
#     - 'Others': 'start/others.md'
# 
# - アプリケーション開発:
#     - '開発について': 'dev/dev.md'
#     - 'Linux 環境の構築': 'dev/env.md'
#     - 'GUIによるパーティションの作成': 'dev/gui.md'
#     - 'Phenox ライブラリについて': 'dev/lib.md'
#     - 'C言語 API' : 'dev/api.md'
#     - 'Python API' : 'dev/pythonapi.md'
#     - 'パラメーター一覧' : 'dev/param.md'
#     - '状態量一覧' : 'dev/state.md'
#     - '用語集' : 'dev/glossary.md'
- Tutorials:
    - 'Streaming with mjpg-streamer': 'tut/mjpgstreamer.md'
#     - 'プロジェクトのビルド' : 'tut/build.md'
#     - 'Phenox の飛行' : 'tut/controll.md'
#     - '画像配信サーバープログラム': 'tut/server.md'
#     - 'Pythonによるプログラム実行' : 'tut/python_basic.md'
#     - 'Pythonコードによる飛行' : 'tut/python_hover.md'
#     - 'FAQ': 'faq.md'
#     - '付録': 'appendix.md'

